### PR TITLE
Fixes images which are too big 

### PR DESCRIPTION
**Pull request by nicksavov**
Fixes joomla-extensions/install-from-web-server#17

Moves joomla-extensions/install-from-web-server#21 from server-side to client-side.

### CODE REVIEW

**Comment by beat** [comment]
From code-review point of view looks good to me :+1:

**Comment by nicksavov** [comment]
Can you double check the minified version? I just used http://cssminifier.com/

Is there a Joomla best practice for minification?

**Comment by beat** [comment]
We would need someone doing a test with client-side joomla debug off to check the minified version. :-)

**Comment by losedk** [comment]
Tested. Works fine

**Comment by nicksavov** [comment]
Thanks @losedk !

**Comment by beat** [comment]
Thanks @nicksavov for the fix and @losedk for the test :+1: 
Merging!

**Pull request merged**
