### PR TITLE
Hide the animation when changing tab

### PR DESCRIPTION
**Pull request by dgt41**

### CODE REVIEW

**Comment by zero-24** [comment]
@test successful

**Comment by zero-24** [comment]
I gues we can set this to RTC :smile:

**Comment by gunjanpatel** [comment]
Instead of hiding it, how is to append it only in web specific div? I means,
In following code of javascript in file `plugins/installer/webinstaller/js/client.js`

```javascript
jQuery('<div id="appsloading"></div>')
	.css("background", "rgba(255, 255, 255, .8) url('../media/jui/img/ajax-loader.gif') 50% 15% no-repeat")
	.css("top", jQuery('#myTabContent').position().top - jQuery(window).scrollTop())
	.css("left", jQuery('#myTabContent').position().left - jQuery(window).scrollLeft())
	.css("width", jQuery('#myTabContent').width())
	.css("height", jQuery('#myTabContent').height())
	.css("position", "fixed")
	.css("z-index", "1000")
	.css("opacity", "0.80")
	.css("-ms-filter", "progid:DXImageTransform.Microsoft.Alpha(Opacity = 80)")
	.css("filter", "alpha(opacity = 80)")
	.appendTo('#myTabContent');
```

we do following change,
```javascript
jQuery('<div id="appsloading"></div>').appendTo('#myTabContent #web');
```

In this way it's scope will be only limited to `#web` div.

**Comment by dgt41** [comment]
Thanks @gunjanpatel for the suggestion, this is way better!
I will close this one as it is included in #23
Please test that one!

**Comment by gunjanpatel** [comment]
Thanks @dgt41 for sending new fix.
Tested `#23` and added comment.

**Pull request closed without merging**
