### PR TITLE
Fixed Ajax spinning image for sites in sub-folders

### PR DESCRIPTION
**Pull request by beat**
This fixes the small issue for sub-folder introduced by #23 .

### CODE REVIEW

**Comment by 810** [comment]
Only change also on .min file, then its ok +1

**Comment by beat** [comment]
Added minified CSS file

**Comment by beat** [comment]
Fixed the min version (used another CSS minifier)

**Comment by dgt41** [comment]
works here, thanks Beat!

**Comment by beat** [comment]
Thanks @810 and @dgt41 ! merging.

**Pull request merged**
