### PR TITLE
use https in the update server

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
simple change.

code review.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
in there interrest in this or can i close this?

**Comment by andrepereiradasilva** [comment]
anyone?

**Comment by zero-24** [comment]
@beat ?

**Comment by beat** [comment]
@zero-24 @andrepereiradasilva we need 1-2-3 testers confirming that works for them here before I can merge this PR... Code-wise looks fine.

**Comment by zero-24** [comment]
?

**Comment by beat** [comment]
Merged, thanks!

**Comment by beat** [comment]
Deployed. Should shortly become available in your Joomla extensions updates.

**Pull request merged**
