### PR TITLE
Ensure the tab loads in fringe cases in recent Joomla versions

### LINKED ISSUE #50: Install the install from web fails to load on page load
Install from github joomla-cms master at revision 351b778254893d1ebbd734a88e3ad2a33b386aff

Login to admin 

Install the install from web with the button provided 

see that it fails to load the content all the time

screen shot 2016-12-11 at 15 28 57

To make it load this correctly you can click another tab and then click the Install from web tab

screen shot 2016-12-11 at 15 32 04

Cross posted to https://github.com/joomla/joomla-cms/issues/13165

### PR DESCRIPTION
**Pull request by PhilETaylor**
Adds an additional check on page load, and if the tab content has not been initialized, but the tab is shown, then load the content. 

This Closes #50

### CODE REVIEW

**Comment by PhilETaylor** [comment]
thats because (i think) com_patchtester is only for the main Joomla-Cms repo and not this one.

**Comment by zero-24** [comment]
You need to select the install from web client configuration in the backend options.

**Comment by Webdongle** [comment]
@PhilETaylor 

Thought that was the case.  Sorry unable to test as I use com_patchtester

**Comment by zero-24** [comment]
Please check the options in com_patchtester.. Other way arround is to manually edit the file mention in this PR ;)

**Comment by mbabker** [comment]
@Webdongle Install the com_patchtester 3.0 beta and in the component config it has a predefined mapping for install from web.  But you should have this plugin installed before trying to apply patches.

**Comment by Webdongle** [comment]
@mbabker 

I don't understand 'predefined mapping'.  All I know is install com_patchtester >> load the patches >>> find the patch and activate to see if that causes the problem.

**Comment by zero-24** [comment]
@Webdongle did you ever opend the Options (there is a options button in the list view).

There you can enter your github accounts and change the traget repo.

**Comment by PhilETaylor** [comment]
Go to com_patchfinder
click options menu icon
select the correct project and click save
reload the data

**Comment by mbabker** [comment]
Check the component options, you can configure it to pull PRs from different repos.

**Comment by Webdongle** [comment]
OK found 'GitHub Project Repository' in the options but no list.  What value do I give that field ?

**Comment by mbabker** [comment]
If you're using the stable 2.0.1 package then in the "GitHub Project Owner" field put in `joomla-extensions` and in the "GitHub Project Repository" field put in `install-from-web-client`.

If you're using the beta 3.0 package then it's a select list.

**Comment by mbabker** [comment]
Basically it's always whatever you see at the top of the page for the repo name or the first two URL path segments (the first part is the owner and the second part is the repo name).  Works with any GitHub repository that basically follows the main CMS file structure.

**Comment by zero-24** [comment]
(or the weblinks repo structure) *run and hide*

**Comment by Webdongle** [comment]
Patch works as expected

Using patchtester 3beta found it 👍 

Before applying patch
Navigate to Extensions >>> Manage >>> Install from web ... Fail
Click 'Install from folder' tab  then click ' Install from web' tab again ... success
Navigate to Extensions >>> Manage >>> database then back to Extensions >>> Manage >>> Install from web ... Fail


After applying patch
Navigate to Extensions >>> Manage >>> Install from web ... success
Click 'Install from folder' tab  then click ' Install from web' tab again ... success
Navigate to Extensions >>> Manage >>> database then back to Extensions >>> Manage >>> Install from web ... success

Thanks everyone for your patience.

**Comment by RickR2H** [comment]
Successfully tested this patch! Thanks!

**Comment by beat** [comment]
@Webdongle and @RickR2H Thanks! as we have 2 successful tests here, marking as ready to merge after code review (will do later today)!

**Comment by beat** [comment]
@Webdongle @RickR2H (and others too) if you have another few spare minutes, we have another test missing here:
https://github.com/joomla-extensions/install-from-web-server/pull/36#issuecomment-296429000
(it requires editing a file in the webinstaller to point to the staging server which has a caching issue fix). Would be great to deploy all together with Joomla 3.7 release.

**Comment by Webdongle** [comment]
@beat 

Had a look at that thread but not sure how to test to see if the patch fixes it.

**Comment by beat** [comment]
@Webdongle Way easiest of all for joomla-extensions/install-from-web-server#36 is to just edit your webinstaller.php file in your local install as instructed in my comment here: https://github.com/joomla-extensions/install-from-web-server/pull/36#issuecomment-296429000 . With that you can test the new server version.

**Comment by Webdongle** [comment]
Oh so it's a new version of Install from web.  OK see now

**Comment by RickR2H** [comment]
Am I missing something? When I go to a default Joomla 3.6.5 install and open: plugins/installer/webinstaller/webinstaller.php

The URL is already there: public $appsBaseUrl = 'https://appscdn.joomla.org/webapps/';

**Comment by Webdongle** [comment]
Yes you are missing
and change the webapps to **staging** to test it

**Comment by RickR2H** [comment]
@Webdongle how can I do this...?

**Comment by Webdongle** [comment]
@RickR2H 
https://github.com/joomla-extensions/install-from-web-server/pull/36#issuecomment-296429000

**Comment by Webdongle** [comment]
Did this get merged because the problem still exists in my site after update to 3.7.0 ?

**Comment by PhilETaylor** [comment]
No this is not yet merged :(

**Comment by beat** [comment]
Will be merged and deployed today :smile:

**Comment by Webdongle** [comment]
Just in time for 3.7.1

**Comment by PhilETaylor** [comment]
This plugin is distributed separately to Joomla, and so is not dependant on a Joomla release being made - it can be deployed at any time.

**Comment by Webdongle** [comment]
And how are the files for the plugin to be updated if not done with a Joomla update ?

**Comment by mbabker** [comment]
The same way any Joomla extension is updated, you get the notification in the backend and update through the Extension Manager.

**Comment by Webdongle** [comment]
Ahhhhhhhhhhhhh ... I always miss the bleeding obvious

**Comment by beat** [comment]
Merged! Thanks!

**Comment by beat** [comment]
Deployed. Should shortly become available in your Joomla extensions updates.

**Pull request merged**
